package com.rebater.cash.well.fun.green;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.rebater.cash.well.fun.bean.AdvertiBean;
import com.rebater.cash.well.fun.bean.LogEvent;
import com.rebater.cash.well.fun.bean.PayDbDetail;

import com.rebater.cash.well.fun.green.AdvertiBeanDao;
import com.rebater.cash.well.fun.green.LogEventDao;
import com.rebater.cash.well.fun.green.PayDbDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig advertiBeanDaoConfig;
    private final DaoConfig logEventDaoConfig;
    private final DaoConfig payDbDetailDaoConfig;

    private final AdvertiBeanDao advertiBeanDao;
    private final LogEventDao logEventDao;
    private final PayDbDetailDao payDbDetailDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        advertiBeanDaoConfig = daoConfigMap.get(AdvertiBeanDao.class).clone();
        advertiBeanDaoConfig.initIdentityScope(type);

        logEventDaoConfig = daoConfigMap.get(LogEventDao.class).clone();
        logEventDaoConfig.initIdentityScope(type);

        payDbDetailDaoConfig = daoConfigMap.get(PayDbDetailDao.class).clone();
        payDbDetailDaoConfig.initIdentityScope(type);

        advertiBeanDao = new AdvertiBeanDao(advertiBeanDaoConfig, this);
        logEventDao = new LogEventDao(logEventDaoConfig, this);
        payDbDetailDao = new PayDbDetailDao(payDbDetailDaoConfig, this);

        registerDao(AdvertiBean.class, advertiBeanDao);
        registerDao(LogEvent.class, logEventDao);
        registerDao(PayDbDetail.class, payDbDetailDao);
    }
    
    public void clear() {
        advertiBeanDaoConfig.clearIdentityScope();
        logEventDaoConfig.clearIdentityScope();
        payDbDetailDaoConfig.clearIdentityScope();
    }

    public AdvertiBeanDao getAdvertiBeanDao() {
        return advertiBeanDao;
    }

    public LogEventDao getLogEventDao() {
        return logEventDao;
    }

    public PayDbDetailDao getPayDbDetailDao() {
        return payDbDetailDao;
    }

}
