package com.rebater.cash.well.fun.util.pre;

public class SelfValue {
    public static final String USER_level = "jtt4efd";
    public static final String USER_INVITEICON = "frytfef";
    public static final String USER_ID = "j7uy5grg";
    public static final String USER_EMAIL = "f4t4t3d";
    public static final String USER_CODE= "f4t43fr43d";
    public static final String COUNTRY_ID= "ki7u54d";
    public static final String ISFIRST= "dfg2e3f5";
    //    public static final String QUIZZES_SWIPE_HISTORYTIMES = "vcrg5rfd4r";
//    public static final String QUIZZES_SWIPE_KNOWLEDGETIMES = "cdws3dssgd";
    public static final String WALLET_ACCOUNT= "rg44fr3r3d";
    //    public static final String PER_COUNT= "t7u83re3fd";
    public static final String PER_TIME= "grgj4orj4ef";
    public static final String PER_COUNTRY= "fr5yt5t3";
    public static final String IS_TOAST= "rt53de3w2";
    public static final String IS_SHOW_GUIDE= "gbh4edwed";
    public static final String GAID= "nef4dfed";
    public static final String ISVPSNXCS = "frt32def";
    public static final String IS_SHOW_DOWN= "fed3tr5y3f";
    public static final String recommended_code= "wd4r4fwd";
    public static final String FIRSTRWARD= "fth734r3d";
    public static final String NETSTATUS = "GJRI48T5RE";
    public static final String MAX_COUNT= "frg5tg33d";
    //    public static final String  VIDEO_COUNT= "yjfd345yt78";
    public static final String  ANDEIS= "JU64GTDER4G";
    public static final String  IS_Log= "jneghte";
    public static final String  IS_GAME= "gfrggrfrf";
    public static final String  IS_WALL= "gkjj84r523d";
    public static final String content = "get65yh6";
    public static final String url = "grh64fef3e";
    public static final String pkg = "g6ytr3e2e";
    public static final String type = "ery6yu3rf";
    public static final String IS_BANNER= "f5y3r3de3";
    public static final String IS_PUSH= "f5y5r3dw";
    public static final String P100DATE= "efy6y4f3d";
    public static final String CHANNEL= "erf53e23d";
    public static final String AFFLY= "rg67u4r3e";
    public static final String KOVAO= "efr5y653d";
    public static final String Push_count= "f5ty62sws";
    public static final String ABTYPE= "rg6u764rf3";
    public static final String SUB1= "egt6y3e23de";
    public static final String  PUSH_DATE= "r5yh6y63";
    public static final String  current_count= "wr4tg53dr3";
    public static final String  IS_HREF= "wr5yh7u54r";
    public static final String  STEPDAY= "FRFRF3fr4r";
    public static final String  RUNSTEP= "f3erwde";
    public static final String  CONFIGID= "IFHEF394E33D";
    public static final String SUB2= "jtt5ygrgr";
    public static final String SUB3= "yyt5grtr";
    public static final String SUB4 = "y7i54t4t";
    public static final String SUB5 = "g5yy3ry74fd";
    public static final String ISFINISHSTEP = "hr4tegfee";
    public static final String ISNOTIFY = "FRGE4T6UY74G";
    public static final String FIRSTdAY = "JTYH6Y534TD3R";
    public static final String LOADTIME = "HRIkh7gd55d";//contact_reward6.21增加等待解析时间
    public static final String ISRATE = "fgyh6h89ef";//是否显示评论控制权限开关
    public static final String VIDEODAY = "fgjkdjf43r";//日期
    public static final String VIDEOCOUNT = "gswr4tefff";//视频限制
    public static final String CRRENCY = "hi5t4tefegfg";//b币种
    public static final String ISpermission = "ththyjthth";//授权
    public static final String RATEMONEY = "jyhyhyht";//汇率
    public static final String PAYNAME = "hgk94t0efr4werf";//支付名称
    public static final String ISPAYSHOW = "dffGR5DR4T5EFEF";//支付名称
}
